# 设置世界重生点, 我一般用来给 pvp 世界单独一个重生点, 这样就不用玩家整天 back 了
设置世界重生点:
  启用: false
  世界列表:
    # 世界名: x, y, z, yaw(玩家左右扭头的角度), pitch(玩家上下扭头的角度)
    world_pvp: "-0.5, 100, 0.5, -90, 0"

# 设置玩家的命令补全, 这样玩家就不会补全出没权限的指令了
# 玩家需要退出游戏重进才会生效
设置命令补全:
  启用: false
  补全列表:
    - "tpa"
    - "tpahere"
    - "tpaccept"

# 因为不想用原版的地狱门所以整了个地狱们随机传送, 会取消生物进入地狱门功能, 并且执行一个指令
# 还能防止一些通过地狱门刷东西的bug: 地狱门+驴 地狱门+漏斗矿车 等, 在 1.12.2 版本我曾经被这两个 BUG 折磨得痛不欲生
# 常用的随机传送插件有: betterrtp, essentialsX, residence 等
地狱门随机传送:
  启用: false
  世界列表:
    # 在 world_nether 世界进入地狱门时执行的指令, 传送到 world 世界
    world_nether: "rtp world world"
    # 在 world 世界进入地狱门时执行的指令, 传送到 world_nether 世界
    world: "rtp world world_nether"

# 防止绑定诅咒南瓜头之类的戴上脱不下的物品, 只要是无限耐久的物品绑定诅咒都无法成功附魔
反无限耐久绑定:
  启用: false

# 物品丢弃保护, 全局禁止玩家丢弃物品, 防止误丢弃, 使用 /drop 指令暂时允许丢弃
物品丢弃保护:
  启用: false
  # 使用 /drop 指令后 100 tick 内允许丢弃 (20 tick = 1 秒, 100 tick = 5 秒)
  允许丢弃时长: 100
  允许丢弃提示: "您现在可以丢弃您的物品了."
  禁止丢弃提示: "请输入/drop指令来丢弃你的物品"

# 隐藏完成成就时聊天栏的提示消息
隐藏成就消息:
  启用: false

# 如果玩家进入一个世界时没有指定权限, 就执行指令
世界进入权限:
  启用: false
  # 下面填禁止进入的世界
  世界列表:
    # 进入 world_test 世界需要权限 enterworld.world_test
    # 如果没权限的话, 会执行列出的指令, 这里让玩家执行 spawn 指令达到禁止进入的效果
    world_test:
      # 以玩家身份执行 spawn 指令
      - "player: spawn"
      # 以控制台身份执行 spawn 指令
      - "console: spawn"
    # 进入 world_test2 世界需要权限 enterworld.world_test2
    world_test2:
      - "player: spawn"
      - "console: spawn"

# 让某个实体不攻击某个实体, 例如末影人不攻击末影螨, 防止小黑刷怪塔
实体目标控制器:
  启用: false
  # 末影人不攻击末影螨
  控制列表:
    ENDERMAN: ENDERMITE

# 玩家手里拿着指定 lore 的物品右键即可将身上的经验储存起来, 左键取出经验
经验银行:
  启用: false
  # lore 的格式如下, 代表这个物品可以储存 100000 经验值
  # 经验容量: 0/100000
  检测关键字: 经验容量
  # 左键一次最多取出 1000 点经验值, 右键一次最多存 1000 经验值
  每次存取经验值上限: 1000
  # 提示消息设为 "" 可以取消提示
  存入提示: "存入经验: %exp%"
  取出提示: "取出经验: %exp%"
  上限提示: "经验瓶已满, 无法再存入经验"
  无法取出提示: "经验值为0, 无法取出"

# 当玩家长时间静止不动时会弹出一个箱子, 需要点击绿色玻璃板通过验证
# 验证极简化, 不采用复杂的验证机制, 最小化验证码对玩家体验的影响
# 用最小的成本防住 99% 的钓鱼机, 挂机挖矿等
挂机验证码:
  启用: false
  # 每 600 秒尝试触发一次验证码
  检测间隔: 600
  # 每次有 30% 的概率会触发验证码, op 和拥有 VerificationCode.bypass 权限的不会触发验证码
  触发概率: 30
  验证通过按钮: "&a点击通过挂机验证"
  # 如果在十秒内没有通过验证, 执行验证失败指令
  验证超时时长: 10
  验证失败指令:
    - "player: spawn"
    - "console: spawn"
  验证通过消息: "恭喜你通过验证"

# 有些技能插件会使用到雷电，雷电会导致玩家掉落物被破坏
# 开启之后就可以解决这个问题，很方便
防止雷电破坏掉落物:
  启用: false

# 移除原版附魔物品生成, 箱子, 猪灵交易, 村民交易, 附魔台附魔, 附魔装备, 附魔书
移除原版附魔物品生成:
  启用: false

# 支持 Authme 的简易登录, 无需打 /reg 和 /l 指令注册登录
# 直接打开聊天栏输入密码即可，例如你的密码是 123456 直接按下回车输入 123456
简易登录:
  启用: false

# 变量 %FanCount_bilibili_<uuid>%
粉丝计数器:
  启用: false

# 用镐子挖掘方块时会添加一行 lore
# 来记录玩家用这个镐子破坏了多少个方块
挖掘计数器:
  启用: false
  lore内容: "&a挖掘数量: &b%count%"
  # 默认会记录镐子，斧头，铲子
  需要计数的工具:
    - "SHOVEL"
    - "AXE"
    - "PICKAXE"

# 拉杆配合一个区块的红石阵加鼠标连点器可以快速崩服，防御高频的插件作出反应的时候服已经差不多崩了
# 该功能可以限制拉杆的速度，防止玩家利用拉杆与红石阵崩服
反快速拉杆:
  # 1000 毫秒内仅允许 3 次拉杆操作
  启用: false
  时间: 1000
  次数: 3
  提示消息: "拉杆速度过快，请稍后重试"

# 防止玩家踩坏农田
农田防踩踏:
  启用: false

# 防止实体爆炸，可优化性能或是让世界不会变得坑坑洼洼
爆炸保护:
  启用: false

# 检测玩家身上是否有特定物品，如果有就禁止带入这个世界
世界物品黑名单:
  启用: false
  世界列表:
    - "world_nether"
  物品列表:
    id:
      - "STONE"
  # 进入后执行指令，强制玩家回城
  执行指令:
    - "player: spawn"

# 拥有权限 ServerToolBox.AutoTool 的玩家会自动选择工具栏中最合适的工具（给予权限后需要下线重上才能生效）
# 指令 /AutoTool 切换开启/关闭自动工具模式
自动化工具:
  启用: false
  可挖掘方块:
    剑:
      - "COBWEB"
    镐子:
      - "STONE"
      - "GRANITE"
      - "POLISHED_GRANITE"
      - "POLISHED_GRANITE"
    斧头:
      - "STONE"
    铲子:
      - "DIRT"
      - "GRASS_BLOCK"
  提示消息: "自动工具模式已 %enable%"

反快速指令:
  # 1000 毫秒内仅允许输入 3 次指令
  启用: false
  时间: 1000
  次数: 3
  提示消息: "&9&l您的指令输入速度过快啦，请稍后再试哟"

反聊天刷屏:
  # 1000 毫秒内仅允许说 3 句话
  启用: false
  时间: 1000
  次数: 3
  提示消息: "&9&l您的聊天速度过快啦，请稍后再试哟"

# 玩家加入时会清理聊天屏幕，去除上个服务器遗留的消息
# 也可以使用指令 /CleanChat 手动清理聊天屏幕
加入清理聊天屏幕:
  启用: false
  # 加入后延时 20 tick 才清理屏幕
  延时: 20

# 某世界禁止使用某指令
世界指令黑名单:
  启用: false
  世界列表:
    world_nether:
      - /fly
      - /cmi spawn
    world_test:
      - /fly
  提示消息: "该指令无法在这个世界使用"

# 防止聊天，命令和铁砧改名出现违禁词，将会被取消操作，使用正则表达式检测
# OP 可以无视违禁词，请不要用 OP 进行测试
违禁词屏蔽:
  启用: false
  命令检测: false
  聊天检测: false
  铁砧检测: false
  提示消息: "您的操作因含有违禁词被阻止"
  违禁词列表:
    - ".*服主.*"

# 当玩家拥有物品改名卡时使用指令消耗一张物品改名卡改名
# 指令为 /ItemNameTag 物品名
# 权限 ItemNameTag.color 允许使用彩色符号
物品改名卡:
  启用: false
  改名卡配置:
    type: STONE
    name: "改名卡"
    lore:
      - "使用 /ItemNameTag 物品名 指令"
      - "消耗一张物品改名卡对物品改名"
  提示消息:
    无物品命名牌: "您手上没有物品命名牌"
    手上无物品: "您手上没有物品"
    物品数量过多: "一张命名牌只能修改一个物品"
    修改成功: "恭喜修改成功哟"
    帮助消息: "使用 /ItemNameTag name 物品名 来修改手上物品的名字"

# 当末地被种植上蘑菇时，蘑菇会无限繁殖，并且小黑拿起蘑菇后不占用刷怪上限
# 导致末地会生成很多末影人，导致服务器卡顿，具体可看这个视频 https://www.bilibili.com/video/BV1854y1H7Hd
防止末地蘑菇传播:
  启用: false