# 设置世界重生点, 我一般用来给 pvp 世界单独一个重生点, 这样就不用玩家整天 back 了
设置世界重生点:
  启用: false
  世界列表:
    # 世界名: x, y, z, yaw(玩家左右扭头的角度), pitch(玩家上下扭头的角度)
    world_pvp: "-0.5, 100, 0.5, -90, 0"

# 设置玩家的命令补全, 这样玩家就不会补全出没权限的指令了
# 玩家需要退出游戏重进才会生效
设置命令补全:
  启用: false
  补全列表:
    - "tpa"
    - "tpahere"
    - "tpaccept"

# 因为不想用原版的地狱门所以整了个地狱们随机传送, 会取消生物进入地狱门功能, 并且执行一个指令
# 还能防止一些通过地狱门刷东西的bug: 地狱门+驴 地狱门+漏斗矿车 等, 在 1.12.2 版本我曾经被这两个 BUG 折磨得痛不欲生
# 常用的随机传送插件有: betterrtp, essentialsX, residence 等
地狱门随机传送:
  启用: false
  世界列表:
    # 在 world_nether 世界进入地狱门时执行的指令, 传送到 world 世界
    world_nether: "rtp world world"
    # 在 world 世界进入地狱门时执行的指令, 传送到 world_nether 世界
    world: "rtp world world_nether"


# 防止绑定诅咒南瓜头之类的戴上脱不下的物品, 只要是无限耐久的物品绑定诅咒都无法成功附魔
反无限耐久绑定:
  启用: false


# 物品丢弃保护, 全局禁止玩家丢弃物品, 防止误丢弃, 使用 /drop 指令暂时允许丢弃
物品丢弃保护:
  启用: false
  # 使用 /drop 指令后 100 tick 内允许丢弃 (20 tick = 1 秒, 100 tick = 5 秒)
  允许丢弃时长: 100
  允许丢弃提示: "您现在可以丢弃您的物品了."
  禁止丢弃提示: "请输入/drop指令来丢弃你的物品"

# 隐藏完成成就时聊天栏的提示消息
隐藏成就消息:
  启用: false

# 如果玩家进入一个世界时没有指定权限, 就执行指令
世界进入权限:
  启用: false
  # 下面填禁止进入的世界
  世界列表:
    # 进入 world_test 世界需要权限 enterworld.world_test
    # 如果没权限的话, 会执行列出的指令, 这里让玩家执行 spawn 指令达到禁止进入的效果
    world_test:
      # 以玩家身份执行 spawn 指令
      - "player: spawn"
      # 以控制台身份执行 spawn 指令
      - "console: spawn"
    # 进入 world_test2 世界需要权限 enterworld.world_test2
    world_test2:
      - "player: spawn"
      - "console: spawn"

# 让某个实体不攻击某个实体, 例如末影人不攻击末影螨, 防止小黑刷怪塔
实体目标控制器:
  启用: false
  # 末影人不攻击末影螨
  控制列表:
    ENDERMAN: ENDERMITE

# 玩家手里拿着指定 lore 的物品右键即可将身上的经验储存起来, 左键取出经验
经验银行:
  启用: false
  # lore 的格式如下, 代表这个物品可以储存 100000 经验值
  # 经验容量: 0/100000
  检测关键字: 经验容量
  # 左键一次最多取出 1000 点经验值, 右键一次最多存 1000 经验值
  每次存取经验值上限: 1000
  # 提示消息设为 "" 可以取消提示
  存入提示: "存入经验: %exp%"
  取出提示: "取出经验: %exp%"
  上限提示: "经验瓶已满, 无法再存入经验"
  无法取出提示: "经验值为0, 无法取出"

# 当玩家长时间静止不动时会弹出一个箱子, 需要点击绿色玻璃板通过验证
# 验证极简化, 不采用复杂的验证机制, 最小化验证码对玩家体验的影响
# 用最小的成本防住 90% 的钓鱼机, 挂机挖矿等等, 剩余的 10% 可以手动封禁解决
挂机验证码:
  启用: false
  # 每 600 秒尝试触发一次验证码
  检测间隔: 600
  # 每次有 30% 的概率会触发验证码, op 和拥有 VerificationCode.bypass 权限的不会触发验证码
  触发概率: 30
  验证通过按钮: "&a点击通过挂机验证"
  # 如果在十秒内没有通过验证, 执行验证失败指令
  验证超时时长: 10
  验证失败指令:
    - "player: spawn"
    - "console: spawn"
  验证通过消息: "恭喜你通过验证"

防止雷电破坏掉落物:
  启用: false