name: ServerToolBox
main: com.entiv.servertoolbox.Main
version: ${version}
author: EnTIv
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Authme

commands:
  ServerToolBox:
    description: description
  Drop:
    description: description
  AutoTool:
    description: description
  CleanChat:
    description: description
  ItemNameTag:
    description: description
    aliases:
      - "int"