name: ServerToolBox
main: com.entiv.servertoolbox.Main
version: 1.6
author: EnTIv
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Authme

commands:
  ServerToolBox:
    description: description
  Drop:
    description: description